### ISSUE TITLE
Not enough space

### ISSUE THREAD

**Issue by 2ndalpha** [moul/travis-docker#11]
Hi,

I don't have much experience with Docker but I'm running into an issue with small root volume on Docker in Travis.

Using a simple Dockerfile:
FROM ubuntu:14.04
RUN df -h

Results in Travis:
Filesystem      Size  Used Avail Use% Mounted on
rootfs          985M  317M  669M  33% /
none            985M  317M  669M  33% /
tmpfs           985M     0  985M   0% /dev
shm              64M     0   64M   0% /dev/shm
none            985M  317M  669M  33% /etc/resolv.conf
none            985M  317M  669M  33% /etc/hostname
none            985M  317M  669M  33% /etc/hosts
tmpfs           985M     0  985M   0% /proc/kcore
tmpfs           985M     0  985M   0% /proc/timer_stats

Running it in my local environment root volume is 20GB.
Is there a way to increase the volume? Or am I missing something trivial here?
Thanks in advance :)

**Comment by moul** [comment]
It seems that the storage limit isn't fixed http://docs.travis-ci.com/user/ci-environment/#The-Build-Machine
I will try to check if we can get more spaces

**Comment by moul** [comment]
Can you try to run the `df -h` command outside of the Docker container too ?

**Comment by 2ndalpha** [comment]
Travis itself has plenty of space:
$ df -h
Filesystem             Size  Used Avail Use% Mounted on
/vz/private/210297837  299G  187G   98G  66% /
none                   1.5G  8.0K  1.5G   1% /dev
none                   308M   56K  308M   1% /run
none                   5.0M   12K  5.0M   1% /run/lock
none                   1.5G     0  1.5G   0% /run/shm
/dev/null              768M  168M  601M  22% /var/ramfs
cgroup                 1.5G     0  1.5G   0% /sys/fs/cgroup

**Comment by moul** [comment]
The actual limitation is made by this: https://github.com/moul/travis-docker/blob/master/linux-init#L57
We can try to use a real /var/lib/docker, it will be a little bit slower, but we won't have this limitation to 1GB

**Comment by moul** [comment]
please, try again by replacing:
- `curl -sLo - http://j.mp/install-travis-docker | sh -xe` with
- `curl -sLo - http://j.mp/install-travis-docker | BRANCH=feature-bigstorage sh -xe`

**Comment by William-Yeh** [comment]
Seems that "feature-bigstorage" version will hang the build process.

FYI, https://travis-ci.org/William-Yeh/ansible-nodejs/builds/62416727 logs:

```
...
SLiRP Ready ...
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
FATA[0000] Shutting down daemon due to errors: Unable to get the TempDir under /var/lib/docker: mkdir /var/lib/docker/tmp: permission denied 
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Does anybody have successful build?

**Comment by moul** [comment]
I just pushed an update: https://github.com/moul/travis-docker/commit/6c2fd62a3c7358e0a9aaef3d7223cd74aeabe1a2

Can you try again ? If it still fails, I should have some times tomorrow to check it by myself

**Comment by William-Yeh** [comment]
Still failed: https://travis-ci.org/William-Yeh/ansible-nodejs/builds/62485920

```
...
SLiRP Ready ...
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
FATA[0000] Shutting down daemon due to errors: Unable to get the TempDir under /var/lib/docker: mkdir /var/lib/docker/tmp: permission denied 
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

In the build log, line #537 seems to be running the older version:

```
537   sudo chown -R travis /etc/docker
```

**Comment by alexmarnell** [comment]
Beat me to it. I also gave it a whirl and got the same error message.

**Comment by 2ndalpha** [comment]
Unfortunately it does not work.
Wouldn't it possible to mount a file instead of a ramdisk?
Using dd to create a large file.

**Comment by 2ndalpha** [comment]
I experimented with creating a file, formatting it and mounting but as it turns out kernel in Travis does not support ext2/ext3 filesystems.

**Comment by moul** [comment]
@2ndalpha nice idea, I will continue in the same direction

**Comment by moul** [comment]
Still working on this issue (https://github.com/moul/travis-docker/tree/feature-bigstorage)
I think it will also fix #2 

For you information, my next step is to build a new uml image with monolithic ext4 and loop kernel modules

**Comment by 2ndalpha** [comment]
I see that you have been working hard on resolving the issue. Is there some way we can help you?

**Comment by moul** [comment]
Thank you :)

The most promising solution I'm working on is on this branch: https://github.com/moul/travis-docker/tree/feature-uml

I will have a new uml binary with more kernel modules, I should be able to replace the current tmpfs (with a 2Gib limitation) by something else on disk

If it works, we should bypass the current storage limitation and also make /var/lib/docker permanent (#2)

**Comment by moul** [comment]
Success !

https://travis-ci.org/moul/travis-docker/builds/64619595

```
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-0:13-1408252144-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: <unknown>
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 59.03 GB
 Metadata Space Used: 729.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 4.0.2
Operating System: <unknown>
CPUs: 1
Total Memory: 1.959 GiB
Name: (none)
ID: ONXT:MAHN:BJIC:AHZG:6AH7:TYZ5:TLJW:SEFS:S2RP:IBTA:VLGG:U62Z
KILLING
reboot: System halted
```

I will cleanup commit and merge this in master, then I will need some tests from everyone to switch back quickly if something is broken

**Comment by 2ndalpha** [comment]
Awsome work but unfortunately for me it still does not work.
Also one other Dockerfile fails with same error whick worked before

Error I'm getting: "Bus error - the host /dev/shm or /tmp mount likely just ran out of space"

"df -h" in the beginning of the build:
Filesystem                                                                                         Size  Used Avail Use% Mounted on
/dev/mapper/docker-0:13-32243908-d676cdf5c0d29d227f30049b7eef738bfcbd772d6c73bad753da607ffea1511c  9.8G  231M  9.0G   3% /
tmpfs                                                                                             1003M     0 1003M   0% /dev
shm                                                                                                 64M     0   64M   0% /dev/shm
/dev/root                                                                                          721G  204G  480G  30% /etc/hosts
tmpfs                                                                                             1003M     0 1003M   0% /proc/kcore

**Comment by moul** [comment]
I also get this, I did not identified the source of the problem, I don't know why docker (or something else) is consuming so much /dev/shm

**Comment by moul** [comment]
Can you create a new issue so we can continue outside of this closed pull-request ?

**Comment by 2ndalpha** [comment]
Sure
