### ISSUE TITLE
Stable branch

### ISSUE THREAD

**Issue by 2ndalpha** [moul/travis-docker#18]
Would it be possible to have a separate branch for stable version of travis-docker?
One for stable, one for development. Last changes break my build (see #17 ).

**Comment by moul** [comment]
Yes sure, I will prepare scripts and README.md to explain how to use another branch for testing

**Comment by moul** [comment]
The master branch is now stable, I also begin a versionning with tags so we can go further with new features and new `.travis.yml`

I'm now using `develop` branch as main development branch but I will probably use feature-based branches when needed

I created a new project for testing multiple configurations of travis-docker: https://travis-ci.org/moul/travis-docker-example
