### ISSUE TITLE
Can not pull images... need to update Docker version?

### ISSUE THREAD

**Issue by meirwah** [moul/travis-docker#21]
Pulling repository orius123/dind-ssh
age (latest) from orius123/dind-ssh, Server error: Status 404 while fetching image layer (fe894c1a43e251831fa3fb238046d90e752d381f3d3b3a208601708612f5ee50)

https://travis-ci.org/CloudSlang/cloud-slang-content/jobs/69969211

I think the issue is with the Docker change to Docker Hub Api ... not sure...

**Comment by orius123** [comment]
Do you think that pushing a new images would help? Or download an older version in the script.

**Comment by meirwah** [comment]
No.. I think it's an API change issue with Docker Hub...
And there is no older image for (orius123/dind-ssh) only latest...

**Comment by meirwah** [comment]
seems that Travis download of the image is unstable.. closing this...
