### ISSUE TITLE
travis now officially supports Docker

### ISSUE THREAD

**Issue by gesellix** [moul/travis-docker#32]
see http://docs.travis-ci.com/user/docker/

**Comment by gesellix** [comment]
this is a non-issue, only a heads up to probably update your scripts with less hacks :-)

**Comment by moul** [comment]
Oh nice, I updated the README.md accordingly

**Comment by gesellix** [comment]
:+1:

**Comment by remram44** [comment]
I'm [now](https://github.com/ViDA-NYU/reprozip/commit/68cda790e3f91057b3293df6524ca3533dd4548e) using the official way as well.
Thanks for your work, this has been really useful until this point! :two_hearts:
