### ISSUE TITLE
Upgrade docker

### ISSUE THREAD

**Issue by moul** [moul/travis-docker#6]
Docker 1.5.0 was not installing properly (see #4), so we switched to a hardcoded docker version during installation.

Now the project works again, but it could be useful to have the latest docker features

**Comment by tiborvass** [comment]
@moul please make sure you use `https` as well as `get.docker.com` (if you have something in your sources.list make sure to change that too). Thanks! Let me know if we can help.

**Comment by moul** [comment]
Thanks, it should be fixed, I look the detail of the next build

**Comment by moul** [comment]
Except for `apt-get` travis do by itself, I cannot find any non-ssl url, seems good to me

**Comment by moul** [comment]
We are now running Docker 1.6.0 :)
